### ISSUE TITLE
Move the expand field buttons farther apart in the UI element

### ISSUE THREAD

**Issue by Swilchek** [nio-blocks/conditional_dynamic_fields#3]
This goes for more then just this block, and perhaps it's a user central error - but I would like to request that we try and separate these buttons in a vertical fashion to avoid mis-clicks, which can potentially delete entire fields of work, when the intended function was to ad an additional field. 

See image link below for exact description:

http://pasteboard.co/1XnjOkg.jpg

**Comment by hansmosh** [comment]
This is a UI issue and has been added to the appropriate place in JIRA:
https://neutralio.atlassian.net/secure/RapidBoard.jspa?rapidView=20&view=detail&selectedIssue=NUI-25
